###
POST http://localhost:8000/v1/tasks
Content-Type: application/json

{
  "title": "Test time of executionasdfasdf",
  "description": "Test the time of execution for various tasks"
}
  # "is_completed": true

###
GET http://localhost:8000/v1/tasks

###
GET http://localhost:8000/v1/tasks/1c592c0d-4618-49ce-b043-8d670a6032b3

###
PUT http://localhost:8000/v1/tasks/1c592c0d-4618-49ce-b043-8d670a6032b3
Content-Type: application/json

{
  "is_completed": true
}
  # "title": "All application flow tested",
  # "description": "All application flow tested with new code structure updated.",

###
DELETE http://localhost:8000/v1/tasks/e429fdd9-972b-44db-b6ce-95ad9e2dab6d
